### ISSUE TITLE
使用conda的python报错。

### ISSUE THREAD

**Issue by guyujun** [wizyoung/googletranslate.popclipext#9]
~/Desktop/googletranslate.popclipext-2.1.1/src » Traceback (most recent call last): kunkun@kunkundeMacBook-Pro
  File "translate.py", line 8, in <module>
    import requests
  File "/Users/kunkun/Desktop/googletranslate.popclipext-2.1.1/src/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/Users/kunkun/Desktop/googletranslate.popclipext-2.1.1/src/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/anaconda2/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/anaconda2/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/anaconda2/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/anaconda2/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/anaconda2/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "/anaconda2/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "/anaconda2/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "/anaconda2/lib/python2.7/site-packages/asn1crypto/_int.py", line 52, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/anaconda2/lib/python2.7/platform.py", line 1499, in python_implementation
    return _sys_version()[0]
  File "/anaconda2/lib/python2.7/platform.py", line 1464, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.10 (default, Aug 17 2018, 19:45:58) \n[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]'

**Comment by wizyoung** [comment]
你是怎么做到在桌面运行的？另外针对你的问题本身，可以手动安装requests库试试
